package studentPortal;
import javax.swing.ImageIcon;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.plaf.ColorUIResource;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Font;
import javax.swing.JPasswordField;
import javax.swing.JSeparator;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.JPanel;
import java.awt.Cursor;
import javax.swing.border.LineBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;
import javax.swing.border.EtchedBorder;
import java.sql.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.FlowLayout;
import java.awt.BorderLayout;
import javax.swing.BoxLayout;
import java.awt.GridLayout;
import java.awt.CardLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.awt.Toolkit;



/**
 *
 * @author Elloy Ngipol
 */
public class Log_in_System extends javax.swing.JFrame {

	// ======================== DATA BASE ================
	Content content = new Content();
	DbConnection dbconnection = new DbConnection();
	Connection connection = dbconnection.connection();
	PreparedStatement preparedStatement;
		ResultSet resultSet;
   
	// ==================== CHECK IF  CURERENT LOGGED IN AND CALL FOR CONTENT  DIRECT  ================
	
		
		
		
		
	
    public Log_in_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	setIconImage(Toolkit.getDefaultToolkit().getImage(Log_in_System.class.getResource("/assets/received_1779952115547939.jpeg")));
    	setTitle("Log In");
    	addWindowListener(new WindowAdapter() {
    		@Override
    		public void windowActivated(WindowEvent e) {
    	
    			File loggedIn = new File("/loggedIn");
    	if(loggedIn.mkdir()) {
    		System.out.println("Created");
    	}
    			
    		if(loggedIn.exists()) {
    				
    			String[] usernameStrings = loggedIn.list();
    			
    			if(usernameStrings.length == 1) {
    				System.out.println(usernameStrings[0]);
        			
                    
					content.setLocationRelativeTo(null);
				content.setVisible(true);
					content.sendUsername(usernameStrings[0]);
					
					 dispose();
    				
    			}
			
    				
    				
    				//System.out.println("exist");
    			}
	    			
    			
    			
    			
    			
    		}
    	});
    	setResizable(false);
    	getContentPane().setPreferredSize(new Dimension(700, 500));
    	getContentPane().setSize(new Dimension(500, 500));
    	getContentPane().setMaximumSize(new Dimension(500, 500));
    	setMaximumSize(new Dimension(32767, 32767));

        jPanel1 = new javax.swing.JPanel();
        jPanel1.setPreferredSize(new Dimension(500, 500));
        jPanel1.setBorder(null);
        jPanel1.setBackground(new Color(0,0,0,100));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new Dimension(609, 539));
        jPanel1.setLayout(null);
                
                JPanel panel = new JPanel();
                panel.setForeground(Color.WHITE);
                panel.setBorder(new TitledBorder(new EtchedBorder(EtchedBorder.LOWERED, new Color(255, 255, 255), new Color(160, 160, 160)), "WELCOME ", TitledBorder.CENTER, TitledBorder.TOP, null, Color.WHITE));
                panel.setBackground(Color.BLACK);
                panel.setBounds(114, 109, 484, 292);
                jPanel1.add(panel);
                panel.setLayout(null);
                btnLogin = new javax.swing.JButton();
                btnLogin.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                btnLogin.setBounds(236, 154, 134, 30);
                panel.add(btnLogin);
                btnLogin.setBackground(Color.BLUE);
                btnLogin.setBorder(null);
                
                // ========================= LOG IN BUTTON =======================================
                
                btnLogin.addActionListener(new ActionListener() {
                	@SuppressWarnings("deprecation")
					public void actionPerformed(ActionEvent e) {
                		
                		if(txtUsername.getText().isEmpty() || txtpass.getText().isEmpty()) return;
                		
                		
                		String username = txtUsername.getText();
                		@SuppressWarnings("deprecation")
						String password = txtpass.getText();
                		
                		
                		String query = "SELECT Username,StudentPass FROM Student WHERE BINARY Username =? AND BINARY StudentPass =? ";
                		
                		try {
							preparedStatement = connection.prepareStatement(query);
							preparedStatement.setString(1, txtUsername.getText().trim());
						preparedStatement.setString(2, txtpass.getText().trim());
							
							resultSet= preparedStatement.executeQuery();
							
							if (resultSet.next()) {
								
								
								
								//=============================== LOGGED IN SUCCESS =================
								System.out.println("Login success");
                                      
							
								content.setLocationRelativeTo(null);
								content.setVisible(true);
								content.sendUsername(txtUsername.getText());
								
								dispose();
								
												
								
								
							}else {
								
								lblError.show();
								
								lblError.setText("Incorrect username or password!");
								 
								txtpass.setText("");
								
								
								
							}
							
							
							
						} catch (SQLException e1) {
							// TODO Auto-generated catch block
							e1.printStackTrace();
						}
                		
                		
                	}
                });
                
                
                
                        btnLogin.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 30)); // NOI18N
                        btnLogin.setForeground(Color.WHITE);
                        btnLogin.setText("Log in");
                        txtUsername = new javax.swing.JTextField();
                        
                        txtUsername.setToolTipText("Enter your username");
                        txtUsername.addKeyListener(new KeyAdapter() {
                        	
                        	//===============================================================================
                        	
                        	@Override
                        	public void keyTyped(KeyEvent e) {
                        		
                        		 lblError.hide();
                        		lblError.setText("");
                        		
                        		
                        		
                        		
                        	}
                        });
                        txtUsername.setFont(new Font("Trebuchet MS", Font.PLAIN, 13));
                        txtUsername.setHorizontalAlignment(SwingConstants.CENTER);
                        txtUsername.setBounds(182, 23, 240, 27);
                        panel.add(txtUsername);
                        txtUsername.setForeground(Color.WHITE);
                        txtUsername.setBackground(Color.BLACK);
                        txtUsername.setBorder(null);
                        
                        txtpass = new JPasswordField();
                        txtpass.setToolTipText("Enter your password");
                        txtpass.addKeyListener(new KeyAdapter() {
                        	
                        	//==============================================================================
                        	
                        	@Override
                        	public void keyTyped(KeyEvent e) {
                        		
								lblError.hide();

                        		lblError.setText("");
                        		
                        		
                        		
                        	}
                        });
                        txtpass.setFont(new Font("Trebuchet MS", Font.PLAIN, 13));
                        txtpass.setHorizontalAlignment(SwingConstants.CENTER);
                        txtpass.setBounds(182, 75, 240, 30);
                        panel.add(txtpass);
                        txtpass.setForeground(Color.WHITE);
                        txtpass.setBackground(Color.BLACK);
                        txtpass.setBorder(null);
                        
                        JSeparator separator_1 = new JSeparator();
                        separator_1.setBounds(182, 105, 240, 14);
                        panel.add(separator_1);
                        
                        JSeparator separator = new JSeparator();
                        separator.setBounds(182, 50, 240, 14);
                        panel.add(separator);
                        separator.setForeground(Color.WHITE);
                        separator.setBackground(Color.WHITE);
                        jLabel1 = new javax.swing.JLabel();
                        jLabel1.setBounds(31, 23, 155, 30);
                        panel.add(jLabel1);
                        
                                jLabel1.setFont(new Font("Tw Cen MT Condensed Extra Bold", Font.BOLD, 32)); // NOI18N
                                jLabel1.setForeground(Color.BLUE);
                                jLabel1.setText("Username:");
                                jLabel2 = new javax.swing.JLabel();
                                jLabel2.setBounds(31, 68, 151, 40);
                                panel.add(jLabel2);
                                
                                        jLabel2.setFont(new Font("Tw Cen MT Condensed Extra Bold", Font.BOLD, 32)); // NOI18N
                                        jLabel2.setForeground(Color.BLUE);
                                        jLabel2.setText("Password:");
                                        btnSignUp = new javax.swing.JButton();
                                        btnSignUp.setBorder(null);
                                        btnSignUp.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                                        btnSignUp.setBounds(340, 254, 119, 27);
                                        panel.add(btnSignUp);
                                        btnSignUp.setBackground(Color.BLACK);
                                        
                                                btnSignUp.setFont(new Font("Tw Cen MT Condensed Extra Bold", Font.PLAIN, 26)); // NOI18N
                                                btnSignUp.setForeground(new java.awt.Color(0, 204, 255));
                                                btnSignUp.setText("Sign up");
                                                
                                                JLabel lblNewLabel_1 = new JLabel("New label");
                                                lblNewLabel_1.setToolTipText("c");
                                                lblNewLabel_1.setBounds(51, 113, 97, 100);
                                                panel.add(lblNewLabel_1);
                                                lblNewLabel_1.setIcon(new ImageIcon(Log_in_System.class.getResource("/assets/Icon.png")));
                                                lblNewLabel_1.setBackground(Color.RED);
                                                
                                                lblError = new JLabel("");
                                                lblError.setBounds(182, 116, 240, 27);
                                                panel.add(lblError);
                                                lblError.setBorder(null);
                                                lblError.setOpaque(true);
                                                lblError.setBackground(Color.BLACK);
                                                lblError.setHorizontalAlignment(SwingConstants.CENTER);
                                                lblError.setFont(new Font("STXinwei", Font.PLAIN, 15));
                                                lblError.setForeground(Color.RED);
                                                lblError.hide();
                                                btnSignUp.addActionListener(new java.awt.event.ActionListener() {
                                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                        jButton2ActionPerformed(evt);
                                                    }
                                                });

        pack();
    	getContentPane().setLayout(new CardLayout(0, 0));
    	getContentPane().add(jPanel1, "name_169912577012600");
    	
    	lblNewLabel = new JLabel("");
    	lblNewLabel.setBackground(new Color(0, 0, 0));
    	lblNewLabel.setIcon(new ImageIcon(Log_in_System.class.getResource("/assets/received_1685274575144155.jpeg")));
    	lblNewLabel.setBounds(0, 0, 700, 499);
    	jPanel1.add(lblNewLabel);
    	
    	JPanel penelTitle = new JPanel();
    	penelTitle.setBackground(new Color(0, 0, 0));
    	penelTitle.setBounds(0, 0, 700, 45);
    	jPanel1.add(penelTitle);
    	
    	lblTitle = new JLabel("Student Portal");
    	penelTitle.add(lblTitle);
    	lblTitle.setBackground(new Color(0, 0, 102));
    	lblTitle.setFont(new Font("Trebuchet MS", Font.BOLD, 22));
    	lblTitle.setForeground(new Color(51, 0, 255));
    	lblTitle.setHorizontalAlignment(SwingConstants.CENTER);
    	
    	panel_2 = new JPanel();
    	panel_2.setBounds(0, 454, 700, 45);
    	jPanel1.add(panel_2);
    	panel_2.setLayout(null);
    	
    	lblNewLabel_3 = new JLabel("");
    	lblNewLabel_3.setHorizontalAlignment(SwingConstants.CENTER);
    	lblNewLabel_3.setIcon(new ImageIcon(Log_in_System.class.getResource("/assets/received_1779952115547939.jpeg")));
    	lblNewLabel_3.setBounds(0, 0, 700, 45);
    	panel_2.add(lblNewLabel_3);
    }// </editor-fold>                        
    
    
    
// ================================================== SIGN UP BUTTON ========================
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {   
    	SignUp signUp = new SignUp();
    	signUp.setLocationRelativeTo(null);
    	signUp.setVisible(true);
    	
    	dispose();
    	
    	
    	

    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log_in_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log_in_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log_in_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log_in_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	Log_in_System log_in_System = new Log_in_System();
            	log_in_System.setLocationRelativeTo(null);
                log_in_System.setVisible(true);
            
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtUsername;
    private JPasswordField txtpass;
    private JLabel lblNewLabel;
    private JLabel lblError;
    private JLabel lblTitle;
    private JPanel panel_2;
    private JLabel lblNewLabel_3;
}
